/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.julio.crudalunoscursos.view;

import com.julio.crudalunoscursos.dao.AlunoDAO;
import com.julio.crudalunoscursos.dao.CursoDAO;
import com.julio.crudalunoscursos.dao.GerenciadorConexao;
import javax.swing.JOptionPane;

/**
 *
 * @author julio
 */
public class AdicionarCurso extends javax.swing.JFrame {

    /**
     * Creates new form AdicionarCurso
     */
    public AdicionarCurso() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JButton addCursoConfirmaBtn = new javax.swing.JButton();
        javax.swing.JButton addCursoCancelaBtn = new javax.swing.JButton();
        javax.swing.JLabel addDescricaoCursolbl = new javax.swing.JLabel();
        addDescricaoCursoTxt = new javax.swing.JTextField();
        javax.swing.JLabel jLabel2 = new javax.swing.JLabel();
        javax.swing.JScrollPane jScrollPane1 = new javax.swing.JScrollPane();
        addDescricaoCursoTxtArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Adicionar Curso");

        addCursoConfirmaBtn.setText("Adicionar");
        addCursoConfirmaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCursoConfirmaBtnActionPerformed(evt);
            }
        });

        addCursoCancelaBtn.setText("Cancelar");
        addCursoCancelaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCursoCancelaBtnActionPerformed(evt);
            }
        });

        addDescricaoCursolbl.setText("Descrição:");

        jLabel2.setText("Ementa:");

        addDescricaoCursoTxtArea.setColumns(20);
        addDescricaoCursoTxtArea.setRows(5);
        jScrollPane1.setViewportView(addDescricaoCursoTxtArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(addCursoConfirmaBtn)
                        .addGap(198, 198, 198)
                        .addComponent(addCursoCancelaBtn))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(addDescricaoCursolbl)
                            .addGap(18, 18, 18)
                            .addComponent(addDescricaoCursoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addDescricaoCursolbl)
                    .addComponent(addDescricaoCursoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addCursoConfirmaBtn)
                    .addComponent(addCursoCancelaBtn))
                .addGap(27, 27, 27))
        );

        setSize(new java.awt.Dimension(495, 327));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addCursoCancelaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCursoCancelaBtnActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_addCursoCancelaBtnActionPerformed

    private void addCursoConfirmaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCursoConfirmaBtnActionPerformed
        // TODO add your handling code here:
        String descricao = addDescricaoCursoTxt.getText();
        String ementa = addDescricaoCursoTxtArea.getText();
        
        if(descricao != null && !descricao.equals("")){

        CursoDAO cursoDAO = new CursoDAO(GerenciadorConexao.connect());
        boolean sucesso = cursoDAO.adicionaCurso(descricao, ementa);

        if (sucesso == true) {
            JOptionPane.showMessageDialog(null, "O curso " + descricao + " foi cadastrado com sucesso!");
            dispose();
        } else {
            JOptionPane.showMessageDialog(null, "houve um erro ao cadastrar o curso " + descricao);
        }
        } else {
            JOptionPane.showMessageDialog(null, "A descrição está vazia! Insira uma descrição válida.");
        }
    }//GEN-LAST:event_addCursoConfirmaBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdicionarCurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdicionarCurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdicionarCurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdicionarCurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdicionarCurso().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JTextField addDescricaoCursoTxt;
    javax.swing.JTextArea addDescricaoCursoTxtArea;
    // End of variables declaration//GEN-END:variables

}
