/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.julio.crudalunoscursos.view;

import com.julio.crudalunoscursos.dao.AlunoDAO;
import com.julio.crudalunoscursos.dao.GerenciadorConexao;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author julio
 */
public final class CursosDoAluno extends javax.swing.JFrame {

    /**
     * Creates new form CursosDoAluno
     */
    private int codigoAluno;
    private int codigoCurso;

    public CursosDoAluno() {
        initComponents();

        retornaTabelaAlunos();
    }

    public void retornaTabelaAlunos() {

        DefaultTableModel modelo = (DefaultTableModel) alunoTbl.getModel();
        alunoTbl.setRowSorter(new TableRowSorter(modelo));

        modelo.setRowCount(0);

        AlunoDAO alunoDao = new AlunoDAO(GerenciadorConexao.connect());

        alunoDao.buscaTodosOsAlunos().forEach(a -> {
            modelo.addRow(new Object[]{
                a.getCodigo(),
                a.getNome(),}
            );
        });
    }

    public void retornaTabelaCursosDoAluno(int codigo) {

        DefaultTableModel modelo = (DefaultTableModel) cursosQueAlunoFazTbl.getModel();

        cursosQueAlunoFazTbl.setRowSorter(new TableRowSorter(modelo));

        modelo.setRowCount(0);

        AlunoDAO alunoDao = new AlunoDAO(GerenciadorConexao.connect());

        alunoDao.buscaCursosDoAluno(codigo)
                .getListaDeCursosDoAluno()
                .forEach(a -> {

                    modelo.addRow(new Object[]{
                        a.getCodigo(),
                        a.getDescricao(),}
                    );
                });
    }

    public void retornaTabelaCursosQueAlunoNãoFaz(int codigo) {

        DefaultTableModel modelo = (DefaultTableModel) cursosQueAlunoNaoFazTbl.getModel();

        cursosQueAlunoNaoFazTbl.setRowSorter(new TableRowSorter(modelo));

        modelo.setRowCount(0);

        AlunoDAO alunoDao = new AlunoDAO(GerenciadorConexao.connect());

        alunoDao.buscaCursosQueAlunoNaoFaz(codigo)
                .getListaDeCursosQueAlunoNaoFaz()
                .forEach(a -> {

                    modelo.addRow(new Object[]{
                        a.getCodigo(),
                        a.getDescricao(),}
                    );
                });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JScrollPane jScrollPane1 = new javax.swing.JScrollPane();
        alunoTbl = new javax.swing.JTable();
        javax.swing.JScrollPane jScrollPane2 = new javax.swing.JScrollPane();
        cursosQueAlunoFazTbl = new javax.swing.JTable();
        javax.swing.JLabel cursosDoAlunoLbl = new javax.swing.JLabel();
        javax.swing.JLabel cursosNaoDoAlunoLbl = new javax.swing.JLabel();
        javax.swing.JScrollPane jScrollPane3 = new javax.swing.JScrollPane();
        cursosQueAlunoNaoFazTbl = new javax.swing.JTable();
        deletaCursoDoAlunoBtn = new javax.swing.JButton();
        addCursoDoAluno = new javax.swing.JButton();
        javax.swing.JButton voltaBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cursos do Aluno");

        alunoTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nome"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        alunoTbl.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        alunoTbl.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        alunoTbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                alunoTblMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(alunoTbl);
        if (alunoTbl.getColumnModel().getColumnCount() > 0) {
            alunoTbl.getColumnModel().getColumn(0).setResizable(false);
            alunoTbl.getColumnModel().getColumn(0).setPreferredWidth(1);
        }

        cursosQueAlunoFazTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "", "Descrição"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        cursosQueAlunoFazTbl.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        cursosQueAlunoFazTbl.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        cursosQueAlunoFazTbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cursosQueAlunoFazTblMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(cursosQueAlunoFazTbl);
        if (cursosQueAlunoFazTbl.getColumnModel().getColumnCount() > 0) {
            cursosQueAlunoFazTbl.getColumnModel().getColumn(0).setMinWidth(0);
            cursosQueAlunoFazTbl.getColumnModel().getColumn(0).setPreferredWidth(0);
            cursosQueAlunoFazTbl.getColumnModel().getColumn(0).setMaxWidth(0);
        }

        cursosDoAlunoLbl.setText("Cursos que o aluno faz:");

        cursosNaoDoAlunoLbl.setText("Cursos que o aluno não faz:");

        cursosQueAlunoNaoFazTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "", "Descrição"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        cursosQueAlunoNaoFazTbl.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        cursosQueAlunoNaoFazTbl.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        cursosQueAlunoNaoFazTbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cursosQueAlunoNaoFazTblMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(cursosQueAlunoNaoFazTbl);
        if (cursosQueAlunoNaoFazTbl.getColumnModel().getColumnCount() > 0) {
            cursosQueAlunoNaoFazTbl.getColumnModel().getColumn(0).setMinWidth(0);
            cursosQueAlunoNaoFazTbl.getColumnModel().getColumn(0).setPreferredWidth(0);
            cursosQueAlunoNaoFazTbl.getColumnModel().getColumn(0).setMaxWidth(0);
        }

        deletaCursoDoAlunoBtn.setText("Excluir");
        deletaCursoDoAlunoBtn.setEnabled(false);
        deletaCursoDoAlunoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletaCursoDoAlunoBtnActionPerformed(evt);
            }
        });

        addCursoDoAluno.setText("Adicionar");
        addCursoDoAluno.setEnabled(false);
        addCursoDoAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCursoDoAlunoActionPerformed(evt);
            }
        });

        voltaBtn.setText("Voltar");
        voltaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltaBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 346, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cursosNaoDoAlunoLbl)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(addCursoDoAluno, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(deletaCursoDoAlunoBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(voltaBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(cursosDoAlunoLbl))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 559, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(cursosDoAlunoLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(deletaCursoDoAlunoBtn)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cursosNaoDoAlunoLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(addCursoDoAluno)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(voltaBtn)))))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void alunoTblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_alunoTblMouseClicked
        // TODO add your handling code here:

        DefaultTableModel modeloTbl = (DefaultTableModel) alunoTbl.getModel();

        codigoAluno = Integer.parseInt(modeloTbl.
                getValueAt(alunoTbl.getSelectedRow(), 0).toString());

        retornaTabelaCursosQueAlunoNãoFaz(codigoAluno);
        retornaTabelaCursosDoAluno(codigoAluno);
    }//GEN-LAST:event_alunoTblMouseClicked

    private void voltaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltaBtnActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_voltaBtnActionPerformed

    private void addCursoDoAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCursoDoAlunoActionPerformed
        // TODO add your handling code here:
        AlunoDAO alunoDao = new AlunoDAO(GerenciadorConexao.connect());

        alunoDao.adicionarCursoAoAluno(codigoAluno, codigoCurso);

        retornaTabelaCursosQueAlunoNãoFaz(codigoAluno);
        retornaTabelaCursosDoAluno(codigoAluno);

        addCursoDoAluno.setEnabled(false);
    }//GEN-LAST:event_addCursoDoAlunoActionPerformed

    private void cursosQueAlunoNaoFazTblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cursosQueAlunoNaoFazTblMouseClicked
        // TODO add your handling code here:

        DefaultTableModel modeloTbl = (DefaultTableModel) cursosQueAlunoNaoFazTbl.getModel();

        codigoCurso = Integer.parseInt(modeloTbl.
                getValueAt(cursosQueAlunoNaoFazTbl.getSelectedRow(), 0).toString());

        addCursoDoAluno.setEnabled(true);
    }//GEN-LAST:event_cursosQueAlunoNaoFazTblMouseClicked

    private void cursosQueAlunoFazTblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cursosQueAlunoFazTblMouseClicked
        // TODO add your handling code here:

        DefaultTableModel modeloTbl = (DefaultTableModel) cursosQueAlunoFazTbl.getModel();

        codigoCurso = Integer.parseInt(modeloTbl.
                getValueAt(cursosQueAlunoFazTbl.getSelectedRow(), 0).toString());

        deletaCursoDoAlunoBtn.setEnabled(true);
    }//GEN-LAST:event_cursosQueAlunoFazTblMouseClicked

    private void deletaCursoDoAlunoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletaCursoDoAlunoBtnActionPerformed
        // TODO add your handling code here:
                AlunoDAO alunoDao = new AlunoDAO(GerenciadorConexao.connect());

        alunoDao.excluirCursoDoAluno(codigoAluno, codigoCurso);

        retornaTabelaCursosQueAlunoNãoFaz(codigoAluno);
        retornaTabelaCursosDoAluno(codigoAluno);

        deletaCursoDoAlunoBtn.setEnabled(false);
    }//GEN-LAST:event_deletaCursoDoAlunoBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CursosDoAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CursosDoAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CursosDoAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CursosDoAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CursosDoAluno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JButton addCursoDoAluno;
    javax.swing.JTable alunoTbl;
    javax.swing.JTable cursosQueAlunoFazTbl;
    javax.swing.JTable cursosQueAlunoNaoFazTbl;
    javax.swing.JButton deletaCursoDoAlunoBtn;
    // End of variables declaration//GEN-END:variables
}
