/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.julio.crudalunoscursos.view;

import com.julio.crudalunoscursos.dao.AlunoDAO;
import com.julio.crudalunoscursos.dao.GerenciadorConexao;
import com.julio.crudalunoscursos.validation.Validacao;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author julio
 */
public final class VerAlunos extends javax.swing.JFrame {

    /**
     * Creates new form VerAlunos
     */
    
    int codigoSelecionado;
    
    public VerAlunos() {
        initComponents();

        DefaultTableModel modelo = (DefaultTableModel) verAlunosTbl.getModel();
        verAlunosTbl.setRowSorter(new TableRowSorter(modelo));

        retornaTabelaAlunos();
    }

    public void retornaTabelaAlunos() {
        
        DefaultTableModel modelo = (DefaultTableModel) verAlunosTbl.getModel();
        
        modelo.setRowCount(0);
        
        AlunoDAO alunoDao = new AlunoDAO(GerenciadorConexao.connect());

        alunoDao.buscaTodosOsAlunos().forEach(a -> {
            modelo.addRow(new Object[]{
                a.getCodigo(),
                a.getNome(),}
            );
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JScrollPane jScrollPane1 = new javax.swing.JScrollPane();
        verAlunosTbl = new javax.swing.JTable();
        verAlunosNomeTxt = new javax.swing.JTextField();
        verAlunosAlterarBtn = new javax.swing.JButton();
        verAlunosDeletarBtn = new javax.swing.JButton();
        verAlunosSalvarBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Visualizar Alunos");

        verAlunosTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        }
    );
    verAlunosTbl.setToolTipText("");
    verAlunosTbl.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
    verAlunosTbl.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
    verAlunosTbl.getTableHeader().setReorderingAllowed(false);
    verAlunosTbl.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            verAlunosTblMouseClicked(evt);
        }
    });
    jScrollPane1.setViewportView(verAlunosTbl);
    if (verAlunosTbl.getColumnModel().getColumnCount() > 0) {
        verAlunosTbl.getColumnModel().getColumn(0).setResizable(false);
        verAlunosTbl.getColumnModel().getColumn(0).setPreferredWidth(1);
        verAlunosTbl.getColumnModel().getColumn(1).setResizable(false);
    }

    verAlunosNomeTxt.setEditable(false);

    verAlunosAlterarBtn.setText("Alterar");
    verAlunosAlterarBtn.setEnabled(false);
    verAlunosAlterarBtn.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            verAlunosAlterarBtnActionPerformed(evt);
        }
    });

    verAlunosDeletarBtn.setText("Excluir");
    verAlunosDeletarBtn.setEnabled(false);
    verAlunosDeletarBtn.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            verAlunosDeletarBtnActionPerformed(evt);
        }
    });

    verAlunosSalvarBtn.setText("Salvar");
    verAlunosSalvarBtn.setEnabled(false);
    verAlunosSalvarBtn.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            verAlunosSalvarBtnActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(verAlunosNomeTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(verAlunosAlterarBtn)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(verAlunosSalvarBtn)))
                    .addContainerGap())
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(verAlunosDeletarBtn)
                    .addGap(126, 126, 126))))
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addContainerGap())
                .addGroup(layout.createSequentialGroup()
                    .addComponent(verAlunosNomeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(65, 65, 65)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(verAlunosAlterarBtn)
                        .addComponent(verAlunosSalvarBtn))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 153, Short.MAX_VALUE)
                    .addComponent(verAlunosDeletarBtn)
                    .addGap(60, 60, 60))))
    );

    pack();
    setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void verAlunosTblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verAlunosTblMouseClicked
        // TODO add your handling code here:
        verAlunosNomeTxt.setEditable(false);
        verAlunosAlterarBtn.setEnabled(true);
        verAlunosDeletarBtn.setEnabled(true);

        DefaultTableModel modeloTbl = (DefaultTableModel) verAlunosTbl.getModel();

        String nomeString = modeloTbl.getValueAt(verAlunosTbl.getSelectedRow(), 1).toString();
        verAlunosNomeTxt.setText(nomeString);

        String codigoTblString = modeloTbl.getValueAt(verAlunosTbl.getSelectedRow(), 0).toString();
        codigoSelecionado = Integer.parseInt(codigoTblString);
    }//GEN-LAST:event_verAlunosTblMouseClicked

    private void verAlunosAlterarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verAlunosAlterarBtnActionPerformed
        // TODO add your handling code here:
        
        verAlunosNomeTxt.setEditable(true);
        verAlunosNomeTxt.requestFocusInWindow();
        
        verAlunosSalvarBtn.setEnabled(true);
        verAlunosAlterarBtn.setEnabled(false);
        verAlunosDeletarBtn.setEnabled(false);
    }//GEN-LAST:event_verAlunosAlterarBtnActionPerformed

    private void verAlunosSalvarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verAlunosSalvarBtnActionPerformed
        // TODO add your handling code here:
        
        verAlunosSalvarBtn.setEnabled(false);
        verAlunosDeletarBtn.setEnabled(false);
        
        String nome = verAlunosNomeTxt.getText();
        boolean eValido = Validacao.validaSeEstaVazio(nome);
        
        if(eValido == true){
            
        AlunoDAO alunoDAO = new AlunoDAO(GerenciadorConexao.connect());
        boolean sucesso = alunoDAO.alteraAluno(codigoSelecionado, nome);

        if (sucesso == true) {
            JOptionPane.showMessageDialog(null, "O aluno " + nome + " foi alterado com sucesso!");
            
        } else {
            JOptionPane.showMessageDialog(null, "houve um erro ao alterar o aluno " + nome);
        }
        
        } else {
            JOptionPane.showMessageDialog(null, "O nome está vazio! Insira um nome válido.");
        }
        
        retornaTabelaAlunos();
        
    }//GEN-LAST:event_verAlunosSalvarBtnActionPerformed

    private void verAlunosDeletarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verAlunosDeletarBtnActionPerformed
        // TODO add your handling code here:
        
        AlunoDAO alunoDAO = new AlunoDAO(GerenciadorConexao.connect());
        
        String nome = verAlunosNomeTxt.getText();
        boolean sucesso = alunoDAO.excluiAluno(codigoSelecionado);

        if (sucesso == true) {
            JOptionPane.showMessageDialog(null, "O aluno " + nome + " foi excluido com sucesso!");
            
        } else {
            JOptionPane.showMessageDialog(null, "houve um erro ao excluir o aluno " + nome +".");
        }
        
        retornaTabelaAlunos();
    }//GEN-LAST:event_verAlunosDeletarBtnActionPerformed
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VerAlunos.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VerAlunos.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VerAlunos.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VerAlunos.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VerAlunos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JButton verAlunosAlterarBtn;
    javax.swing.JButton verAlunosDeletarBtn;
    javax.swing.JTextField verAlunosNomeTxt;
    javax.swing.JButton verAlunosSalvarBtn;
    javax.swing.JTable verAlunosTbl;
    // End of variables declaration//GEN-END:variables
}
