/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.julio.crudalunoscursos.view;

import com.julio.crudalunoscursos.dao.CursoDAO;
import com.julio.crudalunoscursos.dao.GerenciadorConexao;
import com.julio.crudalunoscursos.validation.Alertas;
import com.julio.crudalunoscursos.validation.Validacao;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author julio
 */
public final class VerCursos extends javax.swing.JFrame {

    /**
     * Creates new form VerAlunos
     */
    int codigoSelecionado;

    public VerCursos() {
        initComponents();

        retornaTabelaCursos();
    }

    public void retornaTabelaCursos() {

        DefaultTableModel modelo = (DefaultTableModel) verCursosTbl.getModel();

        verCursosTbl.setRowSorter(new TableRowSorter(modelo));

        modelo.setRowCount(0);

        CursoDAO cursoDao = new CursoDAO(GerenciadorConexao.connect());

        cursoDao.buscaTodosOsCursos().forEach(a -> {
            modelo.addRow(new Object[]{
                a.getCodigo(),
                a.getDescricao(),
                a.getEmenta()}
            );
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JScrollPane verCursosTblScroll = new javax.swing.JScrollPane();
        verCursosTbl = new javax.swing.JTable();
        verCursosDescricaoTxt = new javax.swing.JTextField();
        verCursosAlterarBtn = new javax.swing.JButton();
        verCursosDeletarBtn = new javax.swing.JButton();
        verCursosSalvarBtn = new javax.swing.JButton();
        javax.swing.JButton verCursosVoltarBtn = new javax.swing.JButton();
        javax.swing.JLabel verCursosDescricaoLbl = new javax.swing.JLabel();
        javax.swing.JLabel verCursosEmentaBtn = new javax.swing.JLabel();
        javax.swing.JScrollPane jScrollPane2 = new javax.swing.JScrollPane();
        verCursosEmentaTxtField = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Visualizar Cursos");

        verCursosTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Descrição", "null"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        verCursosTbl.setToolTipText("");
        verCursosTbl.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        verCursosTbl.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        verCursosTbl.getTableHeader().setReorderingAllowed(false);
        verCursosTbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                verCursosTblMouseClicked(evt);
            }
        });
        verCursosTblScroll.setViewportView(verCursosTbl);
        if (verCursosTbl.getColumnModel().getColumnCount() > 0) {
            verCursosTbl.getColumnModel().getColumn(0).setResizable(false);
            verCursosTbl.getColumnModel().getColumn(0).setPreferredWidth(1);
            verCursosTbl.getColumnModel().getColumn(1).setResizable(false);
            verCursosTbl.getColumnModel().getColumn(2).setMinWidth(0);
            verCursosTbl.getColumnModel().getColumn(2).setPreferredWidth(0);
            verCursosTbl.getColumnModel().getColumn(2).setMaxWidth(0);
        }

        verCursosDescricaoTxt.setEditable(false);

        verCursosAlterarBtn.setText("Alterar");
        verCursosAlterarBtn.setEnabled(false);
        verCursosAlterarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verCursosAlterarBtnActionPerformed(evt);
            }
        });

        verCursosDeletarBtn.setText("Excluir");
        verCursosDeletarBtn.setEnabled(false);
        verCursosDeletarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verCursosDeletarBtnActionPerformed(evt);
            }
        });

        verCursosSalvarBtn.setText("Salvar");
        verCursosSalvarBtn.setEnabled(false);
        verCursosSalvarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verCursosSalvarBtnActionPerformed(evt);
            }
        });

        verCursosVoltarBtn.setText("Voltar");
        verCursosVoltarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verCursosVoltarBtnActionPerformed(evt);
            }
        });

        verCursosDescricaoLbl.setText("Descrição:");

        verCursosEmentaBtn.setText("Ementa:");

        verCursosEmentaTxtField.setEditable(false);
        verCursosEmentaTxtField.setColumns(20);
        verCursosEmentaTxtField.setRows(5);
        jScrollPane2.setViewportView(verCursosEmentaTxtField);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(verCursosTblScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 311, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(verCursosDescricaoLbl)
                        .addComponent(verCursosDescricaoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(verCursosEmentaBtn))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(verCursosAlterarBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(verCursosSalvarBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(verCursosVoltarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(verCursosDeletarBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(verCursosDescricaoLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(verCursosDescricaoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(verCursosEmentaBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2)
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(verCursosAlterarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(verCursosDeletarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(verCursosSalvarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(verCursosVoltarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(verCursosTblScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 424, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void verCursosTblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verCursosTblMouseClicked
        // TODO add your handling code here:
        verCursosDescricaoTxt.setEditable(false);
        verCursosEmentaTxtField.setEditable(false);

        verCursosAlterarBtn.setEnabled(true);
        verCursosDeletarBtn.setEnabled(true);

        DefaultTableModel modeloTbl = (DefaultTableModel) verCursosTbl.getModel();

        String codigoTblString = modeloTbl.getValueAt(verCursosTbl.getSelectedRow(), 0).toString();
        codigoSelecionado = Integer.parseInt(codigoTblString);

        String descricaoString = modeloTbl.getValueAt(verCursosTbl.getSelectedRow(), 1).toString();
        verCursosDescricaoTxt.setText(descricaoString);

        String ementaString = modeloTbl.getValueAt(verCursosTbl.getSelectedRow(), 2).toString();
        verCursosEmentaTxtField.setText(ementaString);
    }//GEN-LAST:event_verCursosTblMouseClicked

    private void verCursosAlterarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verCursosAlterarBtnActionPerformed
        // TODO add your handling code here:

        verCursosDescricaoTxt.setEditable(true);
        verCursosDescricaoTxt.requestFocusInWindow();

        verCursosEmentaTxtField.setEditable(true);

        verCursosSalvarBtn.setEnabled(true);
        verCursosAlterarBtn.setEnabled(false);
        verCursosDeletarBtn.setEnabled(false);
    }//GEN-LAST:event_verCursosAlterarBtnActionPerformed

    private void verCursosSalvarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verCursosSalvarBtnActionPerformed
        // TODO add your handling code here:

        String descricao = verCursosDescricaoTxt.getText();
        String ementa = verCursosEmentaTxtField.getText();

        boolean eValido = Validacao.validaSeEstaVazio(descricao);

        if (eValido == true) {

            CursoDAO cursoDAO = new CursoDAO(GerenciadorConexao.connect());
            boolean sucesso = cursoDAO.alteraCurso(codigoSelecionado, descricao, ementa);

            Alertas.alertaAlterarCurso(sucesso, descricao);

        } else {
            JOptionPane.showMessageDialog(null, "A descrição está vazia! Insira uma descrição válida.");
        }

        verCursosDescricaoTxt.setText("");
        verCursosEmentaTxtField.setText("");

        verCursosSalvarBtn.setEnabled(false);
        verCursosDeletarBtn.setEnabled(false);

        retornaTabelaCursos();

    }//GEN-LAST:event_verCursosSalvarBtnActionPerformed

    private void verCursosDeletarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verCursosDeletarBtnActionPerformed
        // TODO add your handling code here:

        int desejaExcluir = JOptionPane.showConfirmDialog(rootPane, "Deseja realmente excluir o curso " +
                verCursosDescricaoTxt.getText() + "?",
                "Deseja excluir?",
                JOptionPane.YES_NO_OPTION);
        
        if(desejaExcluir == 0){
        
        CursoDAO cursoDAO = new CursoDAO(GerenciadorConexao.connect());

        String descricao = verCursosDescricaoTxt.getText();
        boolean sucesso = cursoDAO.excluiCurso(codigoSelecionado);

        Alertas.alertaDeletarCurso(sucesso, descricao);

        verCursosDescricaoTxt.setText("");

        verCursosAlterarBtn.setEnabled(false);
        verCursosDeletarBtn.setEnabled(false);

        verCursosDescricaoTxt.setText("");
        verCursosEmentaTxtField.setText("");

        retornaTabelaCursos();
        }
    }//GEN-LAST:event_verCursosDeletarBtnActionPerformed

    private void verCursosVoltarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verCursosVoltarBtnActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_verCursosVoltarBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VerCursos.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VerCursos.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VerCursos.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VerCursos.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VerCursos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JButton verCursosAlterarBtn;
    javax.swing.JButton verCursosDeletarBtn;
    javax.swing.JTextField verCursosDescricaoTxt;
    javax.swing.JTextArea verCursosEmentaTxtField;
    javax.swing.JButton verCursosSalvarBtn;
    javax.swing.JTable verCursosTbl;
    // End of variables declaration//GEN-END:variables
}
